# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DBeat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod ‘CocoaLumberjack’,’~>2.3.0-rc2'

  # Pods for DBeat

end
